family = "Noto Handwriting COLRv1 Test"
output_file = "NotoHandWritingCOLRv1-Regular.ttf"
color_format = "glyf_colr_1"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = [
  "red_pen/emoji_u270d.svg", 
  "red_pen/emoji_u270d_1f3fb.svg", 
  "red_pen/emoji_u270d_1f3fc.svg", 
  "red_pen/emoji_u270d_1f3fd.svg", 
  "red_pen/emoji_u270d_1f3fe.svg", 
  "red_pen/emoji_u270d_1f3ff.svg"
]

[master.regular.position]
wght = 400
