# This is supposed to work in Firefox and Safari as they support OT-SVG

family = "Noto Handwriting Test"
output_file = "NotoHandWriting-Regular.ttf"
color_format = "glyf_colr_1_and_picosvgz"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = [
  "red_pen/emoji_u270d.svg", 
  "red_pen/emoji_u270d_1f3fb.svg", 
  "red_pen/emoji_u270d_1f3fc.svg", 
  "red_pen/emoji_u270d_1f3fd.svg", 
  "red_pen/emoji_u270d_1f3fe.svg", 
  "red_pen/emoji_u270d_1f3ff.svg"
]

[master.regular.position]
wght = 400
