family = "Noto Handwriting glyf Test"
output_file = "NotoHandWritingglyf-Regular.ttf"
color_format = "glyf"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = [
  "bw/emoji_u270d.svg", 
  "bw/emoji_u270d_1f3fb.svg", 
  "bw/emoji_u270d_1f3fc.svg", 
  "bw/emoji_u270d_1f3fd.svg", 
  "bw/emoji_u270d_1f3fe.svg", 
  "bw/emoji_u270d_1f3ff.svg"
]

[master.regular.position]
wght = 400
